[package]
name = "flars"
version = "0.0.2"
license = "GPL-3.0"
edition = "2021"

[profile.release]
strip = true
#lto = true

[dependencies]
sdl2 = { version = "0.35", features = ["image"] }
tiled-json-rs = "0.2"
toml_edit = { version = "0.19", features = ["serde", "perf"] }
glam = "0.22"
num_enum = "0.5"
ary = "0.1"
serde = { version = "1.0", features = ["derive"] }
