[package]
name = "flars"
version = "0.0.1"
edition = "2021"

[profile.release]
strip = true
# lto = true

[dependencies]
ary = "0.1"
glam = "0.22"

[dependencies.sdl2]
version = "0.35"
features = [
	"image",
#	"bundled",
]
